### PR TITLE
Refactor for consistency

### PR DESCRIPTION
**Pull request by jvivian**

### CODE REVIEW

**Comment by jvivian** [comment]
Hey @tpesout — mind taking a quick glance? I didn't feel it necessary to touch the plotting code and I stopped short of writing the consolidation step (I left a `TODO`).

 I want to get this repo up on jenkins CI, so I'm going to assign some tickets wrt tests, adding a consolidation step (for graphing output / primary output), and updating the README.

**Comment by tpesout** [comment]
Yeah, I'll take a look at this and come up later today to talk about it

**Comment by jvivian** [comment]
I can now execute the project entrypoint, `toil-rnaseq-sc` from the venv after adding version dependencies and fixing some matplotlib backend garbage. 

I won't worry about bugs in running this until tests are added.

**Comment by jvivian** [comment]
@tpesout — Let me know if there's any reason I shouldn't merge this, otherwise I will later tonight.

**Pull request merged**
